version: "0.2"
phases:
  install:
    runtime-version:
      nodejs: 14
pre_build:
  commands:
    - echo "installing dependencies"
    - npm install
buid:
  commands:
    - echo "starting compilation"
    - npm run build:prod
post_build:
  commands:
    - aws s3 rm s3://angularhospitalbucket --recursive
    - aws s3 sync ./dist/system s3://angularhospitalbucket --delete
    - aws cloudfront create-invalidation --distribution-id E1VPAL96F4RYMO
    --paths '/*'

artifacts:
  name: "AngularBuildOutputs"
  files:
    - "**/*"
  base-directory: "dist/system"